- alias: 'power prediction: idle load'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /1
  condition:
  - condition: state
    entity_id: binary_sensor.idle_load
    state: 'on'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.idle_power
      value: '{{ (states.sensor.grid_power.state|float) + (states.sensor.solar_power.state|float)
        }}'
  mode: single
  
- alias: 'power prediction: induction warning'
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.induction_notify
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: notify.family
    data:
      title: The induction might be left on!
      message: You might want to check!
  - service: media_player.play_media
    target:
      entity_id:
      - media_player.foyer_speaker
      - media_player.kitchen_display
    data:
      media_content_id: http://192.168.0.10:8123/local/voices/induction_warning.mp3
      media_content_type: audio/mp3
  mode: single
